### ISSUE TITLE
💡 would like to contribute a to-do-list web development project usig html css and js

### ISSUE THREAD

**Issue by akshatkhatri** [ZeroOctave/ZeroOctave-Javascript-Projects#1074]
### Concise Description

participating for hacktoberfest 2023

### Solution Proposed

would like to add a project

### Sections Completed

- [ ] Concise Description
- [X] Solution Proposed
- [x] Alternative Solutions
- [ ] Additional-Context

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CONTRIBUTING.md) of this project.
- [X] I have checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [X] I have read the [readme](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md) of this repository.

**Comment by Diyamudhale** [comment]
Hello, I would like to work on this issue. Can you please assign it to me?

**Comment by prakashAditya639** [comment]
@akshatkhatri can you please review my pr?
