### ISSUE TITLE
Todo(Note App) not Working 

### ISSUE THREAD

**Issue by deep-69bits** [ZeroOctave/ZeroOctave-Javascript-Projects#339]
**Bug Description**
Note App(Todo) not working

**Expected behavior**
On clicking Add Note button Note should be added 

**Bug Video**

https://user-images.githubusercontent.com/96793524/157631467-c8af936c-701a-4f9b-b286-f13dbcd59000.mp4

### What will I add

- Will make it work _properly(on clicking Add note button note will be added)_
- Will add some more CSS
- Will add dark and light mode

_(I am a 2022 GSSoC  participant)
please Assign these to me_

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [x] To Reproduce
- [x] Expected behavior
- [x] Screenshots
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through the project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by deep-69bits** [comment]
Sorry there was no bug in Todo
