### ISSUE TITLE
Expense Tracker

### ISSUE THREAD

**Issue by horosahil** [ZeroOctave/ZeroOctave-Javascript-Projects#443]
**Is your feature request related to a problem? Please describe.**
Expense calculating can be bit boring but it can be made fun by only entering all the income and expense amount and automatically calculates the current amount.

**Describe the solution you'd like**
It's a simple expense tracker where we can add our income by entering positive amount and expense by entering negative amount and can keep track of our current balance. We can also delete a particular income or expense. For starting from fresh we need to remove all the income or expense. Once entered any income or expense it will reflect your current balance always unless and until if all income or expense is removed.

I am a GSSOC22 participant 

**Describe alternatives you've considered**
It will be built using html, css, javascript

**Additional context**
NA

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).
