### ISSUE TITLE
Multifunctionality To-Do Note app

### ISSUE THREAD

**Issue by aaryahjolia** [ZeroOctave/ZeroOctave-Javascript-Projects#640]
**Is your feature request related to a problem? Please describe.**
I want to add Multifunctionality To-Do Note app that will have many functionality

### Steps Followed✅

- [x] Is your feature request related to a problem? Please describe.

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).
