### ISSUE TITLE
Fully Responsive Tracker-Expense Calculator (HTML, CSS, JavaScript)

### ISSUE THREAD

**Issue by KiranAminPanjwani** [ZeroOctave/ZeroOctave-Javascript-Projects#758]
**Is your feature request related to a problem? Please describe.**
- Mostly, people are not able to take care of their expenses and control their over-budgets.
- I have designed an easy-to-use expense calculator which will help user to calculate their monthly expenses.
- Users can maintain a record of their monthly expenses by saving them as cards and can control their budgets for the next time.

**Describe the solution you'd like**
- I would like to add my Tracker-Expense Calculator project to your website. I am a GSSOC'22 participant, kindly assign this issue to me. Thank you.

**Describe alternatives you've considered**
Same as above.

**Additional context**

![image](https://user-images.githubusercontent.com/90326051/170573834-b9358651-d107-413d-8ba7-3c2cf3926566.png)

![image](https://user-images.githubusercontent.com/90326051/170573946-ada3f509-d73e-454e-ab88-be5b20ae5d5a.png)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through the project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by KiranAminPanjwani** [comment]
@Astrodevil I am a GSSOC'22 participant. Kindly assign this issue to me. Thank you! 😊
