### ISSUE TITLE
#66 To-Do 

### ISSUE THREAD

**Issue by Harsh3363** [ZeroOctave/ZeroOctave-Javascript-Projects#790]
**Describe the bug**
In the To-Do project, an empty item can be added which is a bug that should be fixed.

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

![Screenshot (90)](https://user-images.githubusercontent.com/72756692/182013601-b40cc01a-d1aa-4b24-8f0e-dd0eb3487565.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ ] Describe the bug
- [ ] To Reproduce
- [ ] Expected behavior
- [ ] Screenshots
- [ ] Additional context

### Code of Conduct✅
- [ ] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [ ] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [ ] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Harsh3363** [comment]
Hii 
I would like to fix this bug please assign this to me.

**Comment by AbhishekRP2002** [comment]
hey there ! if it's not assigned to anyone can i be assigned for this issue ?
