### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by Harsh3363** [ZeroOctave/ZeroOctave-Javascript-Projects#803]
**Is your feature request related to a problem? Please describe.**
The To-do List interface is very simple and not soo user friendly 

**Describe the solution you'd like**
I would like to make changes to it and make its UI more user fiendly

**Describe alternatives you've considered**

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Harsh3363** [comment]
Please assign this to me
