### ISSUE TITLE
Expense Tracker Calculator [SSOC]

### ISSUE THREAD

**Issue by Harsh3363** [ZeroOctave/ZeroOctave-Javascript-Projects#817]
**Describe the bug**
Images not loading the Expense Tracker Calculator WebApp

**To Reproduce**

**Expected behavior**

**Screenshots**
![expense-tracker](https://user-images.githubusercontent.com/72756692/183281617-60850c68-9219-45f9-b372-6c8ea031f4aa.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [ ] To Reproduce
- [ ] Expected behavior
- [x] Screenshots
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).
